name: Insta Bot Worker

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Target Instagram Post URL"
        required: true
      chat_id:
        description: "Telegram Chat ID"
        required: true
      cookie_1:
        description: "Base64 Cookie for Account 1"
        required: true
      cookie_2:
        description: "Base64 Cookie for Account 2"
        required: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.run_id }} 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install playwright requests python-dotenv google-generativeai
          # 🚨 Yahan sirf asli Chrome install hoga Chromium ki jagah
          playwright install chrome
          
      - name: Run Bot Worker
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
          CHAT_ID: ${{ github.event.inputs.chat_id }}
          COOKIE_1: ${{ github.event.inputs.cookie_1 }}
          COOKIE_2: ${{ github.event.inputs.cookie_2 }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python worker.py
